import importlib.util
import io
import shutil
import struct
import subprocess
import sys
import tempfile
import unittest
from unittest import mock
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

WORDS_12 = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
WORDS_24 = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon"
PASSWORD = "archive password"
TEST_ROUNDS_POWER = 13

# FIPS-197 Appendix C.3 and NIST SP 800-38A Appendix F.1.5 AES-256 vectors.
AES256_ECB_VECTORS = [
    (
        "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
        "00112233445566778899aabbccddeeff",
        "8ea2b7ca516745bfeafc49904b496089",
    ),
    (
        "603deb1015ca71be2b73aef0857d77811f352c073b6108d72d9810a30914dff4",
        "6bc1bee22e409f96e93d7e117393172a",
        "f3eed1bdb5d2a03c064b5a7e3db181f8",
    ),
    (
        "603deb1015ca71be2b73aef0857d77811f352c073b6108d72d9810a30914dff4",
        "ae2d8a571e03ac9c9eb76fac45af8e51",
        "591ccb10d410ed26dc5ba74a31362870",
    ),
    (
        "603deb1015ca71be2b73aef0857d77811f352c073b6108d72d9810a30914dff4",
        "30c81c46a35ce411e5fbc1191a0a52ef",
        "b6ed21b99ca6f4f9f153e7b1beafed1d",
    ),
    (
        "603deb1015ca71be2b73aef0857d77811f352c073b6108d72d9810a30914dff4",
        "f69f2445df4f9b17ad2b417be66c3710",
        "23304b7a39f9f3ff067d8d8f9e24ecc7",
    ),
]

# NIST CAVP AES Known Answer Test vectors from KAT_AES.zip.
AES256_CAVP_ECB_VECTORS = [
    (
        "ECBGFSbox256.rsp COUNT=0",
        "0000000000000000000000000000000000000000000000000000000000000000",
        "014730f80ac625fe84f026c60bfd547d",
        "5c9d844ed46f9885085e5d6a4f94c7d7",
    ),
    (
        "ECBGFSbox256.rsp COUNT=4",
        "0000000000000000000000000000000000000000000000000000000000000000",
        "91fbef2d15a97816060bee1feaa49afe",
        "1bc704f1bce135ceb810341b216d7abe",
    ),
    (
        "ECBKeySbox256.rsp COUNT=0",
        "c47b0294dbbbee0fec4757f22ffeee3587ca4730c3d33b691df38bab076bc558",
        "00000000000000000000000000000000",
        "46f2fb342d6f0ab477476fc501242c5f",
    ),
    (
        "ECBKeySbox256.rsp COUNT=15",
        "fca02f3d5011cfc5c1e23165d413a049d4526a991827424d896fe3435e0bf68e",
        "00000000000000000000000000000000",
        "179a49c712154bbffbe6e7a84a18e220",
    ),
    (
        "ECBVarTxt256.rsp COUNT=0",
        "0000000000000000000000000000000000000000000000000000000000000000",
        "80000000000000000000000000000000",
        "ddc6bf790c15760d8d9aeb6f9a75fd4e",
    ),
    (
        "ECBVarTxt256.rsp COUNT=127",
        "0000000000000000000000000000000000000000000000000000000000000000",
        "ffffffffffffffffffffffffffffffff",
        "acdace8078a32b1a182bfa4987ca1347",
    ),
    (
        "ECBVarKey256.rsp COUNT=0",
        "8000000000000000000000000000000000000000000000000000000000000000",
        "00000000000000000000000000000000",
        "e35a6dcb19b201a01ebcfa8aa22b5759",
    ),
    (
        "ECBVarKey256.rsp COUNT=255",
        "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        "00000000000000000000000000000000",
        "4bf85f1b5d54adbc307b0a048389adcb",
    ),
]

# NIST SP 800-38A Appendix F.2.5 CBC-AES256 vector.
AES256_CBC_KEY = "603deb1015ca71be2b73aef0857d77811f352c073b6108d72d9810a30914dff4"
AES256_CBC_IV = "000102030405060708090a0b0c0d0e0f"
AES256_CBC_PLAINTEXT = (
    "6bc1bee22e409f96e93d7e117393172a"
    "ae2d8a571e03ac9c9eb76fac45af8e51"
    "30c81c46a35ce411e5fbc1191a0a52ef"
    "f69f2445df4f9b17ad2b417be66c3710"
)
AES256_CBC_CIPHERTEXT = (
    "f58c4c04d6e5f1ba779eabfb5f7bfbd6"
    "9cfc4e967edb808d679f777bc6702c7d"
    "39f23369a9d9bacfa530e26304231461"
    "b2eb05e2c39be9fcda6c19078c6a9d1b"
)

SEVEN_ZIP_KDF_VECTORS = [
    (
        "empty salt, rounds 0",
        0,
        "password",
        "",
        "140053b53e9dd0b594a283c08f6205891b2b7717e32a04e78eaf237208e9d484",
    ),
    (
        "16-byte incrementing salt, rounds 1",
        1,
        "archive password",
        "000102030405060708090a0b0c0d0e0f",
        "f7c5037543f1899577ea3a1d1dfa36a22a03ba6ce8b3c881b54c67ebabbd98e1",
    ),
    (
        "16-byte ff salt, rounds 2",
        2,
        "archive password",
        "ffffffffffffffffffffffffffffffff",
        "47d054cdcdfd6d51dd2f80a5d327908f367aa5693a7e756a468058af84666582",
    ),
    (
        "unicode password, rounds 13",
        13,
        "passphrase with \u00e4",
        "00112233445566778899aabbccddeeff",
        "e4464495f51234dea23c55bb29701d3616fc682875dfc0e9d8cfb9d26e87dc36",
    ),
]

OFFICIAL_7Z_PASSWORD = "known fixture password"
OFFICIAL_7Z_PLAINTEXT = (
    b"# generated by official 7z fixture\n"
    b"mnemonic = \"abandon abandon abandon abandon abandon abandon abandon "
    b"abandon abandon abandon abandon about\"\n"
)

# Generated with 7-Zip 26.02:
# 7z a -t7z -mx=0 -mhe=off -p'known fixture password' known-good.7z backup.txt
OFFICIAL_7Z_COPY_AES_FIXTURE = bytes.fromhex(
    "377abcaf271c0004fdb94e889000000000000000720000000000000030b2e207"
    "a43e51e072c5b3e889ef0d975e3cf60fd1f4b03da285fd7a40992d55f2e4c"
    "dec093ce502771d9eecae2618a61636244c6543ac1ea8af2d704893b0b28"
    "3eba1ef5c43440460208fb8bff62a2cccc68dd14516e688a916601b5dad"
    "973568a7b369dedcddf73a46f58890bc75690b5cabb58e87638830d86f"
    "518eb3eefdd6f45b828ccb629fe761dab52b66ca83b51ecc660104060001"
    "09809000070b0100022406f1070112530fe344b3175dee15fa7deb3084"
    "ef218a44010001000c808e808e00080a01270b60fa0000050119001117"
    "006200610063006b00750070002e007400780074000000190400000000"
    "140a0100c2413907f124dd01150601002080a4810000"
)


def load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


ENCRYPT_BACKUP = load_module("encrypt_backup", ROOT / "encrypt_backup.py")
DECRYPT_BACKUP = load_module("decrypt_backup", ROOT / "decrypt_backup.py")


class StdoutCapture:
    def __init__(self):
        self.buffer = io.BytesIO()

    def write(self, text):
        return len(text)

    def flush(self):
        pass


class BackupArchiveTest(unittest.TestCase):
    def test_aes256_encrypt_matches_known_vectors(self):
        for key_hex, plaintext_hex, ciphertext_hex in AES256_ECB_VECTORS:
            with self.subTest(plaintext=plaintext_hex):
                key = bytes.fromhex(key_hex)
                plaintext = bytes.fromhex(plaintext_hex)
                ciphertext = ENCRYPT_BACKUP.AES256(key).encrypt_block(plaintext)

                self.assertEqual(ciphertext_hex, ciphertext.hex())

    def test_aes256_decrypt_matches_known_vectors(self):
        for key_hex, plaintext_hex, ciphertext_hex in AES256_ECB_VECTORS:
            with self.subTest(ciphertext=ciphertext_hex):
                key = bytes.fromhex(key_hex)
                ciphertext = bytes.fromhex(ciphertext_hex)
                plaintext = DECRYPT_BACKUP.AES256(key).decrypt_block(ciphertext)

                self.assertEqual(plaintext_hex, plaintext.hex())

    def test_aes256_encrypt_matches_nist_cavp_kat_vectors(self):
        for label, key_hex, plaintext_hex, ciphertext_hex in AES256_CAVP_ECB_VECTORS:
            with self.subTest(vector=label):
                key = bytes.fromhex(key_hex)
                plaintext = bytes.fromhex(plaintext_hex)
                ciphertext = ENCRYPT_BACKUP.AES256(key).encrypt_block(plaintext)

                self.assertEqual(ciphertext_hex, ciphertext.hex())

    def test_aes256_decrypt_matches_nist_cavp_kat_vectors(self):
        for label, key_hex, plaintext_hex, ciphertext_hex in AES256_CAVP_ECB_VECTORS:
            with self.subTest(vector=label):
                key = bytes.fromhex(key_hex)
                ciphertext = bytes.fromhex(ciphertext_hex)
                plaintext = DECRYPT_BACKUP.AES256(key).decrypt_block(ciphertext)

                self.assertEqual(plaintext_hex, plaintext.hex())

    def test_aes256_cbc_encrypt_matches_known_vector(self):
        key = bytes.fromhex(AES256_CBC_KEY)
        iv = bytes.fromhex(AES256_CBC_IV)
        plaintext = bytes.fromhex(AES256_CBC_PLAINTEXT)
        ciphertext = ENCRYPT_BACKUP.aes256_cbc_encrypt(plaintext, key, iv)

        self.assertEqual(AES256_CBC_CIPHERTEXT, ciphertext.hex())

    def test_aes256_cbc_decrypt_matches_known_vector(self):
        key = bytes.fromhex(AES256_CBC_KEY)
        iv = bytes.fromhex(AES256_CBC_IV)
        ciphertext = bytes.fromhex(AES256_CBC_CIPHERTEXT)
        plaintext = DECRYPT_BACKUP.aes256_cbc_decrypt(ciphertext, key, iv)

        self.assertEqual(AES256_CBC_PLAINTEXT, plaintext.hex())

    def test_7z_kdf_matches_known_vectors(self):
        for label, rounds_power, password, salt_hex, key_hex in SEVEN_ZIP_KDF_VECTORS:
            with self.subTest(vector=label):
                salt = bytes.fromhex(salt_hex)

                self.assertEqual(
                    key_hex,
                    DECRYPT_BACKUP.derive_7z_key(password, salt, rounds_power).hex(),
                )
                with mock.patch.object(ENCRYPT_BACKUP, "ROUNDS_POWER", rounds_power):
                    self.assertEqual(
                        key_hex,
                        ENCRYPT_BACKUP.derive_7z_key(password, salt).hex(),
                    )

    def test_build_archive_round_trips_12_and_24_word_mnemonics(self):
        for words in (WORDS_12, WORDS_24):
            plaintext = f'mnemonic = "{words}"\n'.encode()

            with self.subTest(word_count=len(words.split())):
                with mock.patch.object(ENCRYPT_BACKUP, "ROUNDS_POWER", TEST_ROUNDS_POWER):
                    archive = ENCRYPT_BACKUP.build_archive(plaintext, PASSWORD)
                filename, decrypted = DECRYPT_BACKUP.decrypt_archive(archive, PASSWORD)

                self.assertEqual("backup.txt", filename)
                self.assertEqual(plaintext, decrypted)

    def test_build_archive_encrypts_metadata_header(self):
        plaintext = f'mnemonic = "{WORDS_12}"\n'.encode()
        token_bytes = [
            bytes([value]) * 16
            for value in (0x11, 0x22, 0x33, 0x44)
        ]

        with mock.patch.object(ENCRYPT_BACKUP, "ROUNDS_POWER", 2):
            with mock.patch.object(ENCRYPT_BACKUP.secrets, "token_bytes", side_effect=token_bytes):
                archive = ENCRYPT_BACKUP.build_archive(plaintext, PASSWORD)

        filename, decrypted = DECRYPT_BACKUP.decrypt_archive(archive, PASSWORD)
        self.assertEqual("backup.txt", filename)
        self.assertEqual(plaintext, decrypted)

        next_header_offset, header_size, _ = struct.unpack("<QQL", archive[12:32])
        clear_header_start = 32 + next_header_offset
        clear_header = archive[clear_header_start:clear_header_start + header_size]

        self.assertEqual(0x17, clear_header[0])
        self.assertNotIn("backup.txt".encode("utf-16-le"), clear_header)
        self.assertNotIn(struct.pack("<L", ENCRYPT_BACKUP.crc32(plaintext)), clear_header)
        self.assertNotIn(b"\x0c" + ENCRYPT_BACKUP.encode_var64(len(plaintext)), clear_header)

        encoded_header_pack_pos, _ = DECRYPT_BACKUP.read_var64_at(clear_header, 2)
        self.assertEqual(1024, encoded_header_pack_pos)

    def test_decrypts_known_official_7z_copy_aes_fixture(self):
        filename, decrypted = DECRYPT_BACKUP.decrypt_archive(
            OFFICIAL_7Z_COPY_AES_FIXTURE,
            OFFICIAL_7Z_PASSWORD,
        )

        self.assertEqual("backup.txt", filename)
        self.assertEqual(OFFICIAL_7Z_PLAINTEXT, decrypted)

    @unittest.skipUnless(shutil.which("7z"), "7z is not available")
    def test_standard_7z_extracts_generated_encrypted_header_archive(self):
        plaintext = f'mnemonic = "{WORDS_12}"\n'.encode()

        with tempfile.TemporaryDirectory() as tmp:
            archive_path = Path(tmp) / "backup.7z"
            with mock.patch.object(ENCRYPT_BACKUP, "ROUNDS_POWER", 2):
                archive_path.write_bytes(ENCRYPT_BACKUP.build_archive(plaintext, PASSWORD))

            result = subprocess.run(
                ["7z", "x", "-so", f"-p{PASSWORD}", str(archive_path)],
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

        self.assertEqual(plaintext, result.stdout)

    @unittest.skipUnless(shutil.which("7z"), "7z is not available")
    def test_decrypts_standard_7z_mhe_copy_aes_archive(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            plaintext_path = tmp_path / "backup.txt"
            plaintext_path.write_bytes(OFFICIAL_7Z_PLAINTEXT)
            archive_path = tmp_path / "backup.7z"

            subprocess.run(
                [
                    "7z",
                    "a",
                    "-t7z",
                    "-mx=0",
                    "-mhe=on",
                    f"-p{OFFICIAL_7Z_PASSWORD}",
                    str(archive_path),
                    plaintext_path.name,
                ],
                check=True,
                cwd=tmp,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            filename, decrypted = DECRYPT_BACKUP.decrypt_archive(
                archive_path.read_bytes(),
                OFFICIAL_7Z_PASSWORD,
            )

        self.assertEqual("backup.txt", filename)
        self.assertEqual(OFFICIAL_7Z_PLAINTEXT, decrypted)

    def test_default_kdf_rounds_are_hardened(self):
        self.assertGreaterEqual(ENCRYPT_BACKUP.ROUNDS_POWER, 24)

    def test_cli_prompts_for_secrets_and_round_trips_backup_txt(self):
        with tempfile.TemporaryDirectory() as tmp:
            archive_path = Path(tmp) / "backup.7z"

            with mock.patch.object(ENCRYPT_BACKUP, "ROUNDS_POWER", TEST_ROUNDS_POWER):
                with mock.patch("builtins.input", return_value=WORDS_12):
                    with mock.patch.object(ENCRYPT_BACKUP.getpass, "getpass", side_effect=[PASSWORD, PASSWORD]):
                        self.assertEqual(0, ENCRYPT_BACKUP.main([str(archive_path)]))

            stdout = StdoutCapture()
            with mock.patch.object(DECRYPT_BACKUP.getpass, "getpass", return_value=PASSWORD):
                with mock.patch.object(sys, "stdout", stdout):
                    self.assertEqual(0, DECRYPT_BACKUP.main([str(archive_path)]))
            decrypted = stdout.buffer.getvalue().decode()

        lines = decrypted.splitlines()
        self.assertEqual(2, len(lines))
        self.assertEqual(f'mnemonic = "{WORDS_12}"', lines[1])

    def test_encrypt_cli_requires_single_archive_argument(self):
        with mock.patch.object(sys, "stderr", io.StringIO()):
            with self.assertRaises(SystemExit) as raised:
                ENCRYPT_BACKUP.main([])
        self.assertEqual(2, raised.exception.code)

        with mock.patch.object(sys, "stderr", io.StringIO()):
            with self.assertRaises(SystemExit) as raised:
                ENCRYPT_BACKUP.main(["backup.7z", "extra"])
        self.assertEqual(2, raised.exception.code)

    def test_decrypt_cli_requires_single_archive_argument(self):
        with mock.patch.object(sys, "stderr", io.StringIO()):
            with self.assertRaises(SystemExit) as raised:
                DECRYPT_BACKUP.main([])
        self.assertEqual(2, raised.exception.code)

        with mock.patch.object(sys, "stderr", io.StringIO()):
            with self.assertRaises(SystemExit) as raised:
                DECRYPT_BACKUP.main(["backup.7z", "extra"])
        self.assertEqual(2, raised.exception.code)

    def test_wrong_password_fails_crc_check(self):
        plaintext = f'mnemonic = "{WORDS_12}"\n'.encode()
        with mock.patch.object(ENCRYPT_BACKUP, "ROUNDS_POWER", TEST_ROUNDS_POWER):
            archive = ENCRYPT_BACKUP.build_archive(plaintext, PASSWORD)

        with self.assertRaisesRegex(ValueError, "wrong password|damaged archive"):
            DECRYPT_BACKUP.decrypt_archive(archive, "wrong password")

    def test_invalid_mnemonic_words_are_rejected(self):
        cases = [
            (" ".join(["abandon"] * 11), "exactly 12 or 24 words"),
            (" ".join((["abandon"] * 11) + ["notaword"]), "unknown BIP39 word"),
        ]

        for mnemonic, message in cases:
            with self.subTest(message=message):
                stderr = io.StringIO()
                with mock.patch.object(ENCRYPT_BACKUP, "build_archive") as build_archive:
                    with mock.patch("builtins.input", return_value=mnemonic):
                        with mock.patch.object(
                            ENCRYPT_BACKUP.getpass,
                            "getpass",
                            side_effect=[PASSWORD, PASSWORD],
                        ):
                            with mock.patch.object(sys, "stderr", stderr):
                                self.assertEqual(1, ENCRYPT_BACKUP.main(["backup.7z"]))

                build_archive.assert_not_called()
                self.assertIn(message, stderr.getvalue())

    def test_decrypts_documented_coldcard_backup_sample_when_available(self):
        sample = ROOT.parent / "coldcard-firmware" / "docs" / "backup.7z"
        if not sample.exists():
            self.skipTest("Coldcard sample archive is not available")

        sample_password = "spice until comfort zoo divide album erode yard inmate change quantum skate"
        filename, decrypted = DECRYPT_BACKUP.decrypt_archive(sample.read_bytes(), sample_password)

        self.assertEqual("ckcc-backup.txt", filename)
        self.assertIn(b"# Coldcard backup file", decrypted)
        self.assertIn(b"mnemonic = ", decrypted)


if __name__ == "__main__":
    unittest.main()
